<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <!-- CSS -->
    <link href="/bower_resources/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/main.css" rel="stylesheet" />
    <!-- Bootstrap core JavaScript -->
    <script src="/bower_resources/jquery/dist/jquery.min.js"></script>
    <script src="/bower_resources/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--  User-defined script -->
    <script type="text/javascript" src="/js/main.js"></script>
  </head>
  <body>
    <div class="container-fluid">
    <!-- Navbar -->
    <nav class="navbar" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">PCBuilder</a>
        </div>
        <?php echo $authFragment; ?>
        <form class="navbar-form" role="search" onSubmit="process_search();">
            <div class="col-xs-0 col-md-3"></div>
            <div class="input-group col-xs-4">
                <input type="text" class="form-control __search" placeholder="Search" value=<?php echo "'" . $search . "'"; ?>>
                <div class="input-group-btn">
                    <button class="btn btn-default">
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </form>
      </div>
    </nav>
    </div>
    <div class="container">
        <?php echo $pageBody; ?>
    </div>
  </body>
</html>
