    <div class="col-xs-12 col-md-6">
        <div class="well">
            <div class="row">
                <div class="col-xs-4 col-md-5">
                    <div class="thumbnail">
                        <img src= <?php echo "\"/img/$image\""?>>
                    </div>
                </div>
                <div class="col-xs-8 col-md-7">
                    <span class="pull-right">
                        <h2><a href = <?php echo "\"/item/$id\""?>><?php echo $name ?></a></h2>
                        <h3><strong>Quantity: </strong> <?php echo $quantity ?></h3>
                        <h3><strong>Cost: </strong> $<?php echo $cost ?></h3>
                        <br><br>
                        <span class="pull-right">
                        <button class="btn btn-lg btn-danger" type="button" onclick=<?php echo "\"delCartItem($id);\""?>>
                            <span class="glyphicon glyphicon-trash"></span> Remove
                        </button>
                        </span>
                    </span>                                        
                </div>                        
            </div>
        </div>
    </div>