  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img style = "height: 150px;" src=<?php echo "'$mediaLink'"; ?>>
      <div class="caption">
        <h4 style="height: 20px; overflow: hidden; text-overflow: ellipsis;"><?php echo $name; ?> asdfasdfafs</h4> 
        <div style="height: 94px; overflow: hidden; text-overflow: ellipsis;"> 
            <p><?php echo $description; ?></p>
        </div>
        <br>
        <div class='row'>
            <div class = "col-xs-6">
                <h4>$<?php echo $price; ?></h4>
            </div>
            <div class = "col-xs-6">
                <a href=<?php echo '"/item/'.$id.'"'; ?> class="btn btn-default" role="button" data-id=<?php echo $id; ?>>More...</a>
            </div>
        </div>
      </div>

    </div>
  </div>