<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href=<?php echo '"'."#COLLAPSE_$i".'"'; ?>>
                <span class="glyphicon glyphicon-triangle-bottom"
                      style="margin-right: 10px"></span><?php echo $name; ?>
            </a>
        </h4>
    </div>
    <div id=<?php echo '"'."COLLAPSE_$i".'"'; ?> class="panel-collapse collapse">
        <table class="table">
            <?php echo $filters; ?>
        </table>
    </div>
</div>
