<div class="row __catalog" data-category=<?php echo $category; ?> data-page=<?php echo $page; ?> data-search=<?php echo $search; ?>>
    <div class="col-sm-4 col-md-3" style="margin-top: 15px;">
        <div class="panel-group">
            <?php echo $panels; ?>
        </div>
    </div>

    <div class="col-sm-8 col md-9"  style="margin-top: 25px;">
        <div class="row">
            <?php echo $breadcrumb; ?>
        </div>
        <div class="row">
            <?php echo $itemCards; ?>
        </div>
        <div class="row">
            <div class="text-center">
                <ul class="pagination col-center">
                    <?php echo $paginationItems; ?>
                </ul>
            </div>
        </div>
    </div>

</div>
