<div class="row">
  <div class="row">
    <?php echo $breadcrumb; ?>
  </div>
  <div class="row">
    <div class="panel panel-default col-xs-12 col-md-6 item-image-div">
      <div class="row">
        <div class="imagePlaceholder">        
          <img src=<?php echo "/img/".$image; ?> 
              class="item-image"
              id="__item-image">
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div id="myCarousel" class="carousel slide">
            <div class="carousel-inner">
                <?php echo $carouselSlides; ?>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
        <div class="row">   
          <div class="col-xs-6">       
            <h3>
              <?php echo $name; ?>
              <br>
              <small>Available in stock: <?php echo $available; ?></small>
            </h3>
          </div>
          <div class="col-xs-6">       
            <span class="pull-right align-middle">
              <h2 style="display:inline-block"><?php echo $price; ?>$</h2>
              &nbsp;&nbsp;
              <button type="button" class="btn btn-lg btn-primary ">
                <span class="glyphicon glyphicon-shopping-cart"></span>
                Buy
              </button>
            </span>
          </div>                                       
        </div>
        <div class="row">   
          <div class="col-xs-12">  
            <h4>
              Description:
            </h4>
            <p>
              <?php echo $description; ?>
            </p>
          </div>
        </div>
    </div>
  </div>
  <div class="row">
    <h3>Specifications:</h3>
    <table class="table table-striped">
      <?php echo $specifications; ?>
    </table>
  </div>
</div>

