<ul class="nav navbar-nav navbar-right">
    <li>
        <span class="navbar-text">
            Hello,&nbsp;<strong><?php echo $firstName; ?></strong>
        </span>
    </li>
    <li>
        <a href="/profile">
            <span class="glyphicon glyphicon-home"></span>
            Profile
        </a>
    </li>       
    <li>
        <a href="/cart">
            <span class="glyphicon glyphicon-shopping-cart"></span>
            Shopping cart
        </a>
    </li>    
    <li>
        <a href="/api/logout">
            <span class="glyphicon glyphicon-user"></span>
            Logout
        </a>
    </li>
</ul>
