<div class="row">
    <div class="col-xs-12">
        <div class="well">
            <div class="row">
                <div class="col-xs-6">
                    <h4>Order #<?php echo $id?></h4>
                    <strong>Created:</strong> <?php echo $created_at ?><br>
                    <strong>Last updated:</strong> <?php echo $updated_at ?><br>
                    <strong>Status:</strong> 
                    <span class=<?php echo "\"$statusClass\"" ?>>
                        <?php echo $status ?>
                    </span>
                    <h4>Cost: $<?php echo $fullCost ?></h4>
                </div>
                <div class="col-xs-6">
                    <h4>Items</h4>   
                    <?php echo $items?>                      
                </div>                        
            </div>
        </div>
    </div>
</div>