<div class="row">
    <div class="col-xs-4">
        <h3>User info</h3>
        <strong>First name:</strong> <?php echo $fname; ?><br>
        <strong>Last name:</strong> <?php echo $lname; ?> <br>
        <strong>Email:</strong> <?php echo $email; ?> <br>
        <strong>Phone:</strong> <?php echo $phone; ?> <br>          
        <h3>Change password:</h3>
        <form>
            <div class="form-group" id="p_pass_form_group">
                <label for="p_pass_field">Password:</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input type="password" class="form-control" id="p_pass_field" placeholder="New password"/>
                </div>
            </div>
            <div class="form-group" id="p_rpass_form_group">
                <label for="p_rpass_field">Repeat password:</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input type="password" class="form-control" id="p_rpass_field" placeholder="Repeat new password" />
                </div>
            </div>
            <button type="button" class="btn btn-block btn-default" onclick="process_change_password()">Change password</button>
        </form>
        <div class="alert hidden" id="p_alert" style="margin-top: 10px">
        <!-- Content will be set at runtime  -->
        </div>
    </div>
    <div class="col-xs-8">
        <h3>Orders</h3>
        <?php echo $orders?>
        <nav>
            <ul class="pager">
                <li class=<?php echo "\"previous $newerState\""?>><a href=<?php echo "\"/profile/orders/$prevPage\""?>>&larr; Newer</a></li>
                <li class=<?php echo "\"next $olderState\""?>><a href=<?php echo "\"/profile/orders/$nextPage\""?>>Older &rarr;</a></li>
            </ul>
        </nav>                 

    </div>
</div>